### ISSUE TITLE
Finalize Metadata Model

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mahonia#10]
**ACCEPTANCE**
- [x] Predicate List finalized
- [x] Common vs. ETD specific attributes identified
- [x] OSHU sign off on attributes & Predicates

**WORKING DOCUMENT**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by shanitajohn** [comment]
OHSU approves.
