### ISSUE TITLE
DOI: DOI Registration Error Handling

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mahonia#101]
**STORY**
As an administrator, I would like some breadcrumb if a DataCite registration error occurs, so that I don't have completely silent failures.

**ACCEPTANCE**
- [x] If the job fails due to an error originating with the DOI provider, it retries with a backoff.
- [x] DOI Registration Jobs are retried in a way consistent with other background jobs performed by the system
- [x] DOI Registration Job errors are logged in a consistent way with other background jobs performed by the system
- [x] I can see some evidence of the failure in the sidekiq web-console
- [ ] ~We have run at least 2-3 failure tests to ensure our reporting & notifications are useful~ Will test after deployment.

**Comment by no-reply** [comment]
@mark-dce #185 closes this ticket, with the exception of failure testing.

I'm not entirely clear on what kind of testing we have in mind. We could deliberately trigger failures by entering incorrect credentials or by redirecting`mds.test.datacite.org` to a location that will error.

I'm not sure how useful those tests will be, and wonder whether we shouldn't just close the issue, ingest a lot of items, and see what real errors we get.

**Comment by no-reply** [comment]
It looks like we have incorrect credentials in now, so deploying and ingesting items should trigger some errors.

http://mahonia.curationexperts.com/okcomputer/datacite

I'm not sure why we lost our credentials, which were correct when `okcomputer` went up last week.
