### ISSUE TITLE
Capify the codebase

### ISSUE THREAD

**Issue by acozine** [curationexperts/mahonia#11]
Acceptance:

- [ ] add capistrano
- [ ] by default, deploys master
- [ ] can deploy branches
- [ ] includes basic shared files (blacklight.yml, browse_everything_providers.yml, database.yml, fedora.yml, redis.yml, solr.yml, config/environments/production.rb, config/initializers/hyrax.rb)

**Comment by no-reply** [comment]
Is this a duplicate of #40?

**Comment by mark-dce** [comment]
Yes, It seems like this is covered in #40 and #36
