### ISSUE TITLE
IMPORT: Manually map BePress export to Hyrax metadata

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#134]
**ACCEPTANCE**

- [x] Produce a document that we can refer to when building the CSV importer

**METADATA SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**SAMPLE DATA**
https://docs.google.com/spreadsheets/d/17uAvN5NjK4E_JGUS-psFxcJIq-nwk8ObqNnY5HsIUKg/edit#gid=1778571188

https://docs.google.com/spreadsheets/d/1ArYQZ1sl1NhqEA7rCGNjhErXKUAcYMpHriCI4LuCPsI/edit#gid=1275999334

**Comment by jenlindner** [comment]
I've updated the metadata spreadsheet with a column of ETD-exported BePress terms, mapped to Hyrax terms. Additionally, I added a new worksheet called data-mapping that has a column with all of the BePress terms, a column for matched Hyrax terms, and a column for approximate Hyrax matches (where they seemed reasonable).  This should make it easier to determine what terms might still need to be migrated, if any, and what kind of metadata is appropriate for them, if so. 

https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=1201290981
