### ISSUE TITLE
SYSTEMS: Configure SSL for OHSU environments

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mahonia#177]
**ACCEPTANCE CRITERIA**
- [x] Get certificate for production
- [x] Apply certificate for production
- [x] Get certificate for staging
- [x] Apply certificate for staging
- [x] Get certificate for qa
- [x] Apply certificate for qa
- [x] Get certificate for sandbox (mahonia.curationexperts.com)
- [x] Apply certificate for sandbox

**Comment by bess** [comment]
Certs requested on 10 Jan
As of 25 Jan 2018 we still don't have hostnames or certs for OHSU systems. I have installed `curationexperts.com` hostnames and SSL certs instead and will provide instructions for how to change them over when the OHSU ones are ready.

**Comment by banerjek** [comment]
All certs and domain names set up:

https://scholararchive.ohsu.edu/
https://scholararchive-dev.ohsu.edu/
https://scholararchive-staging.ohsu.edu/
