### ISSUE TITLE
SYSTEMS: basic virus checking

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mahonia#178]
**ACCEPTANCE CRITERIA**

- [x] Install ClamAV on servers
- [ ] Configure application to call ClamAV on new uploads
- [ ] Implement basic logging/notification

**Comment by little9** [comment]
@mark-dce @bess 

I added a role to ansible-samvera to install ClamAV on the server over here:

curationexperts/ansible-samvera#27

**Comment by bess** [comment]
@little9 I'm looking at your ansible-samvera PR now. Thanks!

**Comment by bess** [comment]
ClamAV is installed. See Laevigata for an example of how to configure Hyrax to use it.

**Comment by no-reply** [comment]
@bess I'm self assigning this to pick up work on it in the AM. I'll want a bit of your time to help me get started just before or after check-in, if possible.
