### ISSUE TITLE
SSO: Add Shibboleth configuration to DCE Sandbox

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mahonia#18]
**ACCEPTANCE CRITERIA**
- [x] The codebase is updated to allow Shibboleth authentication
- [x] The DCE demo server uses the DCE test shibboleth server to provide authentication
- [x] Configuration and setup is well documented
- [x] Be able to use database authentication locally

**Comment by bess** [comment]
qa-ohsu.curationexperts.com is set up with shibboleth.

**Comment by bess** [comment]
Setup is documented in the playbook, here: https://github.com/curationexperts/playbook/compare/shibboleth?expand=1
