### ISSUE TITLE
SYSTEMS: Add okcomputer and check that DOI service can connect

### ISSUE THREAD

**Issue by bess** [curationexperts/mahonia#180]
**ACCEPTANCE CRITERIA**
- [x] Add okcomputer endpoint
- [x] Add okcomputer check to ensure that DOI service has necessary config and can connect

**Comment by no-reply** [comment]
I believe this is closed by #184, but it requires manual checking on the server.

**Comment by bess** [comment]
@no-reply I deployed it and it works! 👍
