### ISSUE TITLE
VOCABS: Use ID not label for storing MeSH terms

### ISSUE THREAD

**Issue by little9** [curationexperts/mahonia#190]
**ACCEPTANCE CRITERIA**
The out of the box behavior from autocomplete behavior stores the label for the MeSH term. We need the following behavior: 

- [x] The corresponding URI is stored in Fedora

- [x] The term's URI is shown in the turtle view of the work

This issue is the final portion of #124

**Comment by little9** [comment]
We'll need to find a fix for #196 before we demo this again, I can't get the MeSH terms to import on the demo server

**Comment by jenlindner** [comment]
I imported the terms on the demo server, found what the problem had been and sorted it with a workaround and made a hosting ticket about it for better sorting.
