### ISSUE TITLE
Confirm whether Publisher should be part of metadata

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/mahonia#197]
I don't see it in the spreadsheet, but it's in the bepress exported terms and in the current app code. 

https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

Did it get deleted from the spreadsheet, or is not intended for the app?

**Comment by mark-dce** [comment]
@jenlindner can you add this to the spreadsheet and ask @thornhik to weigh in wether this should be included or ignored?

**Comment by jenlindner** [comment]
I should have been more clear; it's not in the main worksheet, but it is in the worksheet of terms that are in need of decisions, and it's to be excluded from oshu approved import mapping. Pinging @thornhik: I just want to confirm that Publisher is not intended for import mapping? Thanks.

**Comment by thornhik** [comment]
@jenlindner I checked Bepress and the collection's data. We do not use Publisher in the Scholars Archive. Publisher does not need to be imported into Hyrax.

**Comment by jenlindner** [comment]
Thank you @thornhik!
