### ISSUE TITLE
Allow specific users to be selected as Admins

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mahonia#20]
**ACCEPTANCE**
- [x] Document procedure for adding new admin from the console in the Wiki

**Comment by bess** [comment]
I added these instructions in the README ... is that okay? Or did you really mean in the Wiki?

**Comment by mark-dce** [comment]
The readme is great for now.  AND I would like the readme to start being a top-level overview and getting started guide, not the place where everything gets put.  

Thinking about this more, I think we should start exploring really using the docs directory more frequently (cause it's version controlled and therefore syncrhonizable with releases).
