### ISSUE TITLE
ETD: Remove Publisher metadata property from Etds

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/mahonia#203]
**ACCEPTANCE CRITERIA**
 - [x] Publisher does not appear on the form field
 - [x] Publisher does not appear in the show view 
 - [x] Publisher does not appear in the facets; 
 - [x] Publisher does not appear in the search results page;
 - [x] Publisher is auto-populated to `["OHSU Scholar Archive"]` when creating an object through the form; 
 - [ ] Publisher is auto-populated to `["OHSU Scholar Archive"]` when importing an object.

**Comment by no-reply** [comment]
This needs to be reopened and the criteria written. The original work done for this is reverted is #261 to fix several issues caused by the approach.

**Comment by no-reply** [comment]
WIP is at https://github.com/curationexperts/mahonia/tree/silence-publisher

**Comment by no-reply** [comment]
I'm also removing `publisher` from Search Fields, which I think we missed in requirements.
