### ISSUE TITLE
DOI: Datacite credentials are incorrect on sandbox server

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#215]
**ACCEPTANCE CRITERIA** 
- [ ] The correct DataCite credentials are installed on the DCE sandbox server
- [ ] Background jobs can successfully connect to DataCite
- [ ] Citations are successfully registered 
- [ ] Re-deploying does not impact DataCite credentials

**Comment by jenlindner** [comment]
Here's the basics of registering credentials, and authenticating and accessing the Datacite server: https://support.datacite.org/docs/mds-2

**Comment by jenlindner** [comment]
Need the correct credentials.

**Comment by no-reply** [comment]
Something on the Datacite side caused a password change. I have used the "forgotten password" link to change it back to the password on the server.

The credentials on `mahonia.curationexperts.com` are the correct ones and can be used for other test systems.
