### ISSUE TITLE
SYSTEMS: OHSU initial server provisioning

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mahonia#22]
**ACCEPTANCE**
- [x] Determine who will have / need access to the OSHU AWS environments
- [ ] ~Extract required credentials from DCE ansible scripts~
- [ ] ~Create comparable cloud formation scripts for OHSU IT to execute~
- [ ] ~Set up Virtual Private Cloud (VPC) for environments~
- [ ] ~Setup QA/Staging/Production server instances using cloud formation scripting~

Based on our 12/4 call with DCE and OHSU IT (ACC) folks, we're re-envisioning the way we'll approach this:
- [x] Provide DCE public keys to OHSU to provide ssh access to instances provisioned by OHSU
- [x] OHSU to provision three instances on AWS

See #13 for follow-on server configuration tasks to build out the Samvera stack

**Comment by shanitajohn** [comment]
Bess and Mark  will have AWS credentials

**Comment by mark-dce** [comment]
@bess - if we use the process we've been using so far, we only need to tell OHSU IT that we need servers with ssh access and the necessary ports open - i.e. we wouldn't necessarily even need AWS access.  Thoughts?

**Comment by mark-dce** [comment]
@f0rer0 & @shanitajohn to schedule time for OHSU and DCE to dig into next steps
