### ISSUE TITLE
OBJECT MODEL: Ensure Embargoes Expire correctly

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mahonia#23]
**ACCEPTANCE CRITERIA** 
- [x] ~Create an ETD with an embargo that has already expired, confirm expiration~ 
- [x] Create an ETD that expired yesterday, confirm expiration (12/3)
- [x] Create an ETD that expires on the day of the demo, confirm expiration (12/4)
- [x] Create an ETD that expires next month, confirm expiration (1/5/18)
- [x] Create an ETD with a lease that will take effect on the day of the demo (12/4)
- [x] Create an ETD with a lease that will end take effect the day after the demo (12/5)

**Comment by shanitajohn** [comment]
Cannot set an embargo to a date in the past.
![Screen Shot 2017-12-01 at 3.10.16 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216454f26b7191a37bf1132b4f5e595ecc3c4a4356bcbbd671f3e57862804e0ee485690972923812a4b1821cbc01ba22dd1ed3beb48945d2f42f67b6d5db1063474f4dcbed5727a19041c95df749e04b57a3133560e2772431.png)
