### ISSUE TITLE
SYSTEMS: get fully qualified domain names

### ISSUE THREAD

**Issue by bess** [curationexperts/mahonia#234]
**ACCEPTANCE CRITERIA**
- [x] Get DNS names for OHSU servers
- [x] update hostnames and ansible scripts

**Comment by shanitajohn** [comment]
OHSU has a request in for a domain name.

**Comment by banerjek** [comment]
scholararchive.ohsu.edu
scholararchive-dev.ohsu.edu
scholararchive-staging.ohsu.edu
