### ISSUE TITLE
SYSTEMS: Get DataCite credentials onto OHSU servers

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#235]
**ACCEPTANCE CRITERIA**
- [x] Get test DataCite credentials onto the OHSU servers 
- [x] Write up how to change the credentials

**Comment by shanitajohn** [comment]
- Kyle to follow-up on how to deploy credentials

**Comment by bess** [comment]
https://github.com/curationexperts/mahonia/wiki/Managing-Credentials
