### ISSUE TITLE
Determine DOI requirements

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mahonia#24]
**ACCEPTANCE**
- [x] Determine provider (DataCite vs. CrossRef)
- [x] Determine minimum registration metadata requirements

**Comment by no-reply** [comment]
From 2017-10-09 workflow meeting: OHSU is transitioning to DataCite.

  - We want a background job triggered in the Actor Stack to register the DOIs.
  - We will provide a `Registrar` fake to assign fake ids and allow OHSU to implement a DataCite `Registrar` at a later date.
  - There is some interest in making the DOI stubs match the Hyrax catalog stubs. This isn't considered important, but we can revisit at implementation.

**Comment by no-reply** [comment]
The [DataCite](http://schema.datacite.org/) metadata schema defines the minimal metadata. We'll want to validate on this basis and provide a mapping.

**Comment by no-reply** [comment]
@mark-dce @bess I closed this as we have confirmed these details with OHSU today. Please reopen if this doesn't look like a completed ticket to you.

See: #30.
