### ISSUE TITLE
Words "Scholar Archive" are not displaying in citation

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#245]
**Expected behavior**
When I create an ETD a citation should be automatically created. The citation should have the words "Scholar Archive" display in italics. 

**Current behavior**
The citation is being created automatically, but without the words, "Scholar Archive."

**Comment by no-reply** [comment]
This was removed explicitly in ac06724d.

@shanitajohn can we clarify the requirement? My understanding is that we need to have this text in the citation, but it was removed quite deliberately back in December. Can you comment?

**Comment by no-reply** [comment]
Reverting the changes to this file will fix the issue, if that's what we need to do. https://github.com/curationexperts/mahonia/commit/ac06724da0ff79efb01784dc6e4377c1fdfeff0c#diff-92ead42d9adabb2915e8c03cad41498a
