### ISSUE TITLE
Gather any style guides or branding assets

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mahonia#26]
**ASSETS**
- [x] Email to request style guide or branding guidelines
- [x] Gather any pre-exiting visual design guidelines, standards, or assets

**Comment by no-reply** [comment]
https://www.ohsu.edu/xd/digital-identity/

**Comment by mark-dce** [comment]
https://www.ohsu.edu/xd/digital-identity/

**Comment by no-reply** [comment]
From 2017-10-16 Sprint Planning: OHSU stylesheets are highly tailored to the CMS. @banerjek may be the best resource for styling.
