### ISSUE TITLE
License is expected to be single-valued in metadata spreadsheet, but is multivalued in create form

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/mahonia#262]
See https://github.com/curationexperts/mahonia/issues/71 and https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/

**Comment by no-reply** [comment]
This replaces #257

**Comment by mark-dce** [comment]
@shanitajohn @jenlindner Have we discussed the out-of-box default behavior with OHSU?  We can override the default behavior, but that means OHSU is taking on a small additional amount of maintenance during future upgrades.  The alternative is to limit the field to one value by convention among the administrators.  So far, it seems like OHSU has been opting for the out of box behavior and handling these kinds of things by human policy / convention among the administrators.

**Comment by no-reply** [comment]
@mark-dce Our previous discussion around this field is represented at https://github.com/curationexperts/mahonia/issues/71

> check whether license should really be multiple

then https://github.com/curationexperts/mahonia/issues/71#issuecomment-340308910

My recollection is that we had already agreed to use the default behavior, but have somehow mixed up what that is. I'm not sure what we need to do to communicate the real behavior---maybe just change the spreadsheet and mention it at handoff.

**Comment by no-reply** [comment]
We heard back from @banerjek about this, and I believe we can just change the spreadsheet to reflect the status quo.

**Comment by jenlindner** [comment]
Agreed, updating and closing.
