### ISSUE TITLE
Set Up CI

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mahonia#3]
**ACCEPTANCE**
- [x] Travis runs on PRs and commits to master
- [x] Travis runs rubocop
- [x] Travis runs rspec
- [x] rspec tests run in random order

**Comment by mark-dce** [comment]
Blocked until #2 complete

**Comment by no-reply** [comment]
Bullet 2 is blocked pending merge of #27.

**Comment by no-reply** [comment]
Bullets 1, 3 and 4 are in #28 and #29.
