### ISSUE TITLE
Add Creator term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#41]
**ACCEPTANCE CRITERIA**
- [x] When I look at the label for the field it should read "Creator" 
- [x] Attribute name is documented in the spreadsheet 
- [x] Predicate should be inherited from Hyrax basic metadata 
- [x] I can type anything into the form field
~~- [ ] I can type in unconstrained text~~ (duplicate)
- [x] The data type is a string 
- [x] When I look at the search results page I should see the creator for each ETD
- [x] All the creators should show up in single item view as a comma separated list
- [x] When I am filling in the ETD form I can add another creator
- [x] I should be able to search on creator by default 
- [x] I should be able to facet on creator 
- [x] When I look at the .ttl view I should be able to find the creator 

**NOTES**
Attribute name should be creator

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
Blocked by #9
