### ISSUE TITLE
Add Degree Name term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#42]
**ACCEPTANCE CRITERIA**
- [x] When I look at the label for the field it should read "Degree Name" 
- [x] Attribute name is documented in the spreadsheet 
- [x] Predicate should be http://vivoweb.org/ontology/core#AcademicDegree
- [x] I have a way to select valid choices for the degree name
- [ ] The field should autosuggest, but is not strictly constrained to, values in the list below
- [x] The data type is a string 
- [x] I can only select one degree name
- [x] When I look at the catalog search results page I should see the degree name for each ETD
- [x] I should see the degree name on the single item view
- [x] I should be able to facet on degree name
- [x] When I look at the .ttl view I should be able to find the degree name

**Controlled Vocab for Degree  name**
D.N.P.
M.A.
M.B.I.
M.M.I.
M.N.
M.N.A.
M.P.H.
M.S.
M.S.N.
Ph.D.

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
Blocked by #9

**Comment by no-reply** [comment]
`http://vivoweb.org/ontology/core#AcademicDegree` is a class, rather than a predicate. We should look at this.

**Comment by no-reply** [comment]
Work in progress at: https://github.com/curationexperts/mahonia/tree/degree-name-term
