### ISSUE TITLE
Add Recommended Citation term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#43]
**ACCEPTANCE CRITERIA**
- [x] If have filled in the fields on the form, when I view my ETD on the single item page I should see a citation
- [x] The citation should show up only on the single item view 
- [x] The citation should show the creator name 
- [x] The citation should show the title of the ETD 
- [x] The citation should show the publication year (ask OHSU) 
- [x] The citation should show "Scholar Archive" in italics
- [x] The citation should show the DOI (stored in the `identifier` field)
- [x] The citation should show the Fedora ID 
- [x] The citation should the ETD URL
- [x] The citation should reflect the current values in the ETD form 

**REFERENCE**
<img width="565" alt="sample citation" src="https://user-images.githubusercontent.com/3064318/31511685-1f581f00-af4e-11e7-819d-3d24c0681463.png">

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
Recommend using the [`bibtex-ruby`](https://github.com/inukshuk/bibtex-ruby) and/or [`citeproc-ruby`](https://github.com/inukshuk/citeproc-ruby) gems. We should be able to populate a structure with the relevant data and emit an APA citation.

This should be more robust than piecing together a citation from strings, with the added benefit that it will be extensible.

**Comment by no-reply** [comment]
Blocked pending appropriate metadata.

**Comment by mark-dce** [comment]
Unblocked - all supporting fields have been implemented in the metadata model.

**Comment by no-reply** [comment]
WIP is at https://github.com/curationexperts/mahonia/tree/citation
