### ISSUE TITLE
ETD: Everyone should be able to Read a (public) ETD

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#46]
**ACCEPTANCE CRITERIA**
- [x] As an unathenticated user, I should be able to discover "Public" ETDs
- [x] As an unathenticated user, I should be able to view "Public" ETDs
- [x] Authenticated users should have the same access as unauthenticated users
- [x] As an unauthenticated user, I SHOULD NOT be able to discover "Institutional" or "Private" ETDs
- [x] As an unauthenticated user, I SHOULD NOT be able to view "Institutional" or "Private" ETDs
- [x] As an authenticated non-admin, I SHOULD NOT be able to discover "Private" ETDs
- [x] As an authenticated non-admin, I SHOULD NOT be able to view "Private" ETDs

**NOTE:** We believe that all of this functionality currently exists, but would like to allocate a time boxed period to add testing to ensure we don't experience regressions related to this behavior.

**Comment by no-reply** [comment]
https://github.com/curationexperts/mahonia/issues/46
