### ISSUE TITLE
ETD: Administrators should be able to Update an ETD

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#47]
**NOTE:** This is a time boxed ticket to ensure we don't experience regressions in functionality around these behaviors.

- [x] An administrator can edit metadata for an existing ETD
- [x] An administrator can attach an additional file
- [x] An administrator can delete a file
- [x] Changes made during editing are persisted

**Comment by jenlindner** [comment]
There's a pr in all for all of the criteria except adding a newer version of a file, which I couldn't quite get - we want the new file to replace the old one, correct?
