### ISSUE TITLE
METADATA: Add Date (normalized) term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#52]
**ACCEPTANCE CRITERIA**
- [x] When I look at the label for the field it should read "Date" 
- [x] Attribute name is documented in the spreadsheet 
- [x] Predicate should be ::RDF::Vocab::DC11.date
- [x] I have a way to add a date to the ETDs
- [x] I should be able to add multiple Dates (normalized) 
- [ ] ~The data type is Date (EDTF)~ moved to #186
- [x] I should see the Date on the single item view
- [x] I should be able to facet on Date (normalized)
- [x] Date normalized should not be displayed in search

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
The RDF::Literal implementation for the EDTF datatype is at https://github.com/dpla/rdf-edtf

**Comment by no-reply** [comment]
WIP at https://github.com/curationexperts/mahonia/tree/date-edtf
