### ISSUE TITLE
Add Keywords term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#54]
**ACCEPTANCE CRITERIA**

- [x] When I look at the label for the field it should read "Keyword" 
- [x] Attribute name is documented in the spreadsheet 
- [ ] Predicate should be http://schema.org/keywords
- [x] I have a way to add keywords to ETDs
- [x] I should have a way to remove a keyword from ETDs
- [x] I should be able to add multiple keywords
- [x] The data type is a string 
- [x] When I look at the catalog search results page I should see the keywords for each ETD
- [x] I should see the keywords on the single item view
~~- [ ] I should be able to facet on keywords~~
- [x] I can enter unconstrained text in the edit form
- [x] When I look at the .ttl view I should be able to find the keywords

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
>  Predicate should be http://schema.org/keywords

This departs from the Hyrax default (`dc:relation`). Are we :ok_hand: about that? It seems better to me, overall.

**Comment by no-reply** [comment]
>  I have a way to add keywords to ETDs
> I should have a way to remove a keyword from ETDs
> I should be able to add multiple keywords

~~All require javascript for testing. In #82, we test my confirming that the `multi_value` class is in place. Hyrax JS takes care of the rest.~~

~~We should discuss whether feature tests are needed and, if so, whether it is sufficient to test for only one multi-valued form field.~~

This is now all tested according to the established pattern.

**Comment by no-reply** [comment]
>  When I look at the label for the field it should read "Keywords"

@mark-dce This seems slightly awkward. Do we really want to be faceting on `Keywords` but not on `Creators`, for example? In the form fields do we have multiple `Keyword` fields, or multiple `Keywords` fields? 

The Hyrax default is `Keyword`.

The question about `schema:keywords` vs `dc:relation` is also still open. I'm happy to change the Hyrax default predicate, but it's complicated enough that I don't want to do it until I know for sure.

**Comment by mark-dce** [comment]
Definitely `Keyword` singular and not the plural - my bad for typing too fast.  I updated the acceptance criteria.

I like `http://schema.org/keywords` much better than `dc:relation`.  I know that's a departure from Hyrax, but I think it's a good one and I'd be happy to see the Hyrax default change at some point.

**Comment by no-reply** [comment]
All my work on this is up to date on `master`, and it's just the predicate change that remains to close it.
