### ISSUE TITLE
Add School term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#56]
**ACCEPTANCE CRITERIA**
- [ ] When I look at the label for the field it should read "School" 
- [ ] Attribute name is documented in the spreadsheet 
- [ ] Predicate should be http://vivoweb.org/ontology/core#School
- [ ] I have a way to select valid choices for the School
- [ ] The field autosuggests values, but is not strictly constrained to, the list provided below
- [ ] The data type is a string 
- [ ] I can only select one School
- [ ] I should see the School name on the single item view
- [ ] I should be able to facet on degree name
- [ ] When I look at the .ttl view I should be able to find the School

**AUTOSUGGEST VOCAB**
* School of Dentistry
* School of Medicine
* School of Nursing
* School of Public Health

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
`http://vivoweb.org/ontology/core#School` is a class, rather than a property.
