### ISSUE TITLE
Add Department term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#57]
**ACCEPTANCE CRITERIA**
- [x] When I look at the label for the field it should read "Department" 
- [x] Attribute name is documented in the spreadsheet 
- [x] Predicate should be http://vivoweb.org/ontology/core#AcademicDepartment
- [ ] I have a way to select valid choices for the Department
- [ ] I can only choose something that's on the list, I cannot type something else in
- [x] The data type is a string 
- [x] I should only be able to add one Department
- [x] I should see the Departments name on the single item view
- [x] I should be able to facet on Departments
- [x] When I look at the .ttl view I should be able to find the Departments

**CONTROLLED VOCAB**
https://docs.google.com/spreadsheets/d/1W3uTbPtuTWG2JNGbaMYErCQtsuqlecTx3y4yPNG4zfA/edit?usp=sharing

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
`http://vivoweb.org/ontology/core#AcademicDepartment` is not a predicate term; I'd suggest we revisit this selection.
