### ISSUE TITLE
Add ORCID ID term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#58]
**ACCEPTANCE CRITERIA**
- [x] When I look at the label for the field it should read "ORCID" 
- [x] Attribute name is documented in the spreadsheet 
- [x] Predicate should be http://vivoweb.org/ontology/core#orcidId
- [x] The data type is a string 
- [x] I can have more than one ORCID value
- [x] I should see the ORCID(s) on the single item view
- [x] I should not be able to facet on ORCID
- [x] When I look at the .ttl view I should be able to find the ORCID(s)

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
`http://vivoweb.org/ontology/core#orcidId` has a domain of `Person`.

**Comment by no-reply** [comment]
@mark-dce I'm realizing that Hyrax has an ORCID implementation that integrates with the `User` models. I'd like to hold this ticket for discussion about whether that can meet the requirements, here.

**Comment by no-reply** [comment]
The initial implementation will be as a simple plain text metadata field. We plan to demo that and consider other requirements.

**Comment by no-reply** [comment]
> When I look at the label for the field it should read "ORCID ID"
Can we just do `ORCID`? The "id" is redundant.

**Comment by mark-dce** [comment]
Yes, ORCID is fine.  I've updated the acceptance accordingly and noted where multiple ORCIDs might show up.
