### ISSUE TITLE
Add Rights Note term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#59]
**ACCEPTANCE CRITERIA**
- [x] When I look at the label for the field it should read "Rights Note" 
- [x] Attribute name is documented in the spreadsheet 
- [x] Predicate should be ::RDF::Vocab::DC11.rights
- [x] The data type is a string 
- [x] I can have multiple rights notes
- [x] When I look at the catalog search results page I should not see the Rights Note for each ETD
- [x] I should not see the Rights Note on the single item view
- [x] I should not be able to facet on Rights Note
- [x] When I look at the .ttl view I should be able to find the Rights Note

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
WIP is at https://github.com/curationexperts/mahonia/tree/rights-note
