### ISSUE TITLE
Add "Title" term to ETDs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mahonia#60]
**ACCEPTANCE CRITERIA**
- [x] "Title" is a required field for all ETDs
- [x] When I look at the label for the field it should read "Title" (Hyrax default)
- [x] Attribute name is **title** (Hyrax default)
- [x] Predicate should be inherited from Hyrax basic metadata 
- [x] I can type in unconstrained text for the field value
- [x] The data type is a string 
- [x] When I look at the search results page I should see the title for each ETD
- [x] If there are multiple titles, each should show up on the show view starting on a new line
- [x] When I am filling in the ETD form I can add another title
- [x] I should be able to search on terms in the title by default (i.e. index as string with English stemming rules - Hyrax default)
- [x] There should not be a facet for title (Hyrax default)
- [x] When I look at the .ttl view I should be able to find the title(s) 

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
> When I look at the label for the field it should read "Title" (Hyrax default)

I'm planning to skip testing these labels across the board. These are configurations that I wouldn't want to have to change specs for when reconfigured.

**Comment by no-reply** [comment]
In progress at https://github.com/curationexperts/mahonia/tree/title-attr

**Comment by no-reply** [comment]
These requirements are not default hyrax behavior. Did we decide this is what we want to do?

>  When I am filling in the ETD form I can add another title

>  If there are multiple titles, each should show up on the show view starting on a new line

Out of the box, the form does not support adding/editing multiple titles.

**Comment by no-reply** [comment]
Work on this is complete in #80, #82, #84, and #85 pending discussion about the issues raised in https://github.com/curationexperts/mahonia/issues/60#issuecomment-338496134.

**Comment by no-reply** [comment]
I actually take it back re: https://github.com/curationexperts/mahonia/issues/60#issuecomment-338496134. I managed to stand up the server and confirm that this is the default behavior. I've added a test to #82 to confirm.
