### ISSUE TITLE
Test "Date Uploaded" term for ETDs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mahonia#61]
**ACCEPTANCE CRITERIA**
- [x] When I look at the label for the field it should read "Date Uploaded" (Hyrax default)
- [x] Attribute name is **date_created** (Hyrax default)
- [x] Predicate should be inherited from Hyrax basic metadata 
- [x] The system populates the date automatically
- [x] The data type is a date 
- [x] When I look at the search results page I should see upload date for each ETD
- [x] There is only one "Date Uploaded" for the ETD
- [x] There should not be a facet "Date Uploaded"
- [x] When I look at the .ttl view I should be able to find the date_created

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
`date_uploaded` and `date_created` are two different attributes. I don't believe Hyrax sets `date_created` by default. I'm treating this ticket as about `date_uploaded` for the moment.

**Comment by mark-dce** [comment]
@no-reply if I remember the conversation with OHSU correctly, the issue is that they're not really tracking the date the ETD was "created", they're tracking the date it was entered into the system (i.e. Uploaded)  While Hyrax track the machine version of "date uploaded" they wanted a human editable date to track this from an administrative rather than technical standpoint.  It probably merits having a 20 minute conversation with OHSU specifically about dates overall and then mapping that back to tickets as needed.
