### ISSUE TITLE
Add Document Type term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#68]
**ACCEPTANCE CRITERIA**
- [x] When I look at the label for the field it should read "Document Type" (Hyrax default)
- [x] Attribute name is **resource_type** (Hyrax default)
- [x] Predicate should be inherited from Hyrax basic metadata (::RDF::Vocab::DC.type (via Hyrax::BasicMetadata)
- [x] The data type is a  string
- [x] I should be able to add more than one document type
- [x] I should be able to remove a document type I have added 
- [x] When I look at the search results page I should not see document types for each ETD
- [x] I should be able to facet on document types
- [x] When I look at the .ttl view I should be able to find the document types

**LOCAL VOCAB** 
https://docs.google.com/spreadsheets/d/1W3uTbPtuTWG2JNGbaMYErCQtsuqlecTx3y4yPNG4zfA/edit#gid=706297574

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
> When I look at the search results page I should not see document types for each ETD

Is this correct? This is not the Hyrax default behavior.

EDIT: this is also listed as `Y` for "display in search" on the spreadsheet. I'm going to implement that instead.
