### ISSUE TITLE
Add License term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#71]
**ACCEPTANCE CRITERIA**
- [x] When I look at the label for the field it should read "License" (Hyrax default)
- [x] Attribute name is **license** (Hyrax default)
- [x] Predicate should be inherited from Hyrax basic metadata ::RDF::Vocab::DC.rights (via Hyrax::BasicMetadata)
- [x] The data type is a string
~~- [ ] I should be able to add more than one license~~
~~- [ ] I should be able to remove a license I have added~~
- [x] Use CC licensing (& review existing Hyrax implementation licensing & rights) - check whether license should really be multiple
- [x] When I look at the search results page I should not see a license for each ETD
- [x] I should be able to facet on license
- [x] When I look at the .ttl view I should be able to find the license

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
Licenses are single valued by default. I think we should keep that in place.
