### ISSUE TITLE
Add Rights term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#72]
**ACCEPTANCE CRITERIA**
- [x] When I look at the label for the field it should read "Rights" (Hyrax default)
- [x] Attribute name is **rights_statement** (Hyrax default)
~~- [ ] Predicate should be inherited from Hyrax basic metadata 
::RDF::Vocab::DC.rights (via Hyrax::BasicMetadata)~~
- [x] Predicate should be inherited from Hyrax basic metadata 
::RDF::Vocab::EDM.rights (via Hyrax::BasicMetadata)
~~- [ ] The data type is a string~~
- [x] The data type is a URI (rightsstatements.org)
- [x] I should not be able to add more than one Rights statements 
- [x] Vocabulary is controlled 
- [x] When I look at the search results page I should not see Rights for each ETD
- [x] I should be able to facet on Rights
- [x] When I look at the .ttl view I should be able to find the rights

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
This requires upgrade to rc1

**Comment by no-reply** [comment]
WIP is in https://github.com/curationexperts/mahonia/tree/rights-statement-term

Blocked by several open PRs.
