### ISSUE TITLE
Add Summary (Abstract / Description) term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#73]
**ACCEPTANCE CRITERIA**
- [x] When I look at the label for the field it should read "Description" 
- [x] Attribute name is **description** (Hyrax default)
- [x] Predicate should be inherited from Hyrax basic metadata 
::RDF::Vocab::DC11.description (via Hyrax::BasicMetadata)
- [x] The data type is a string
- [x] I should be able to add more than one description
- [x] I should be able to remove a description I have added 
- [x] The description should be unconstrained 
- [x] When I look at the search results page I should see the beginning of the description for each ETD
- [x] On the search results page, the description should truncate after 140 characters 
- [x] On the search results page, after the truncated description I should see a 'view more' link 
- [x] Clicking on the view more link should take me to the single item view where I can read the complete description 
- [x] The description should be included in the search fields
- [x] I should not be able to facet on the description
- [x] When I look at the .ttl view I should be able to find the description

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by no-reply** [comment]
> When I look at the label for the field it should read "Description" (Hyrax default)

The Hyrax Default is `Abstract or Summary`; the spreadsheet reads `Summary/Abstract`. I'm going to leave the default until PR time.

>  I should be able to add more than one summary

The form limits this to a single value by default.

**Comment by no-reply** [comment]
Use Description.
