### ISSUE TITLE
METADATA: Add Available for Download Date term to ETDs

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/mahonia#75]
**ACCEPTANCE CRITERIA**
- [x] I view my ETD on the single item page I should see an Available for Download Date
- [x] The Available for Download Date should show up only on the single item view 
- [ ] ~The Available for Download Date should be **bold**~
- [ ] ~Attribute name should be **embargo_end**~
- [x] The predicate should be  generated dynamically, not stored
- [x] The data type is a date 
- [x] I should only be able to have one Available for Download Date 
- [x] The Available for Download Date should be derived from the embargo
- [x] I should not be able to see the Available for Download Date on the search results page 
- [x] I should not be able to facet on the Available for Download Date 
- [x] When I view the .ttl I should be able to find the Available for Download Date

**SPREADSHEET**
https://docs.google.com/spreadsheets/d/1HZpXyVM8xaZZ9mE2uzsbUmWKbCd6NYJTESOrpQeMa18/edit#gid=0

**Comment by little9** [comment]
@mark-dce @shanitajohn  'The Available for Download Date should be bold', does that mean that the label or the value should be bold? The labels in that table are all bold already.

**Comment by little9** [comment]
@mark-dce @tom https://github.com/curationexperts/mahonia/pull/176 addresses all of this except the label being bold and the date showing up in the TTL. Hyrax already has an attribute `embargo_release_date`, which is everything we want, except the ttl view. I'm not sure how to add that to graph.
