### ISSUE TITLE
When attaching multiple files, the PDF should be assigned as representative

### ISSUE THREAD

**Issue by no-reply** [curationexperts/mahonia#86]
The default Hyrax behavior is to assign the first processed file/fileset as "representative" and as the thumbnail if none is assigned. We had called out in #9 that we want an uploaded PDF to be assigned as representative.

This ticket is to ensure that multiple file attachments work correctly with respect to representative/thumbnail status:

  - [ ] PDFs are automatically identified as representative when uploading a new ETD through the form.
  - [ ] Additional uploaded files *are not* marked representative if a PDF is uploaded as well.

**Comment by mark-dce** [comment]
Superseded by #99
